# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'vkapp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for weather
  pod 'Alamofire', '~> 5.0.0-rc.3'
  pod 'SwiftyJSON', '~> 5.0.0'
  pod 'Kingfisher', '~> 5.2.0'
  pod 'Realm', '~> 4.1.1'
  pod 'RealmSwift', '~> 4.1.1'
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
end
